name: gluten_freeway
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using flutter pub publish. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  
  # Required dependencies for your project
  google_maps_flutter: ^2.10.0 #navigation
  geolocator: ^9.0.2
  google_maps_flutter_web: ^0.5.0
  flutter_polyline_points: ^1.0.0
  bcrypt: ^1.1.3 # For hashing passwords
  mongo_dart: ^0.10.4  # For MongoDB interaction
  cupertino_icons: ^1.0.8  # iOS style icons

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/GlutenFreewayLogo.png
    - assets/GlutenFreewayDemoLogo.png